/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeeksRouteImport } from './routes/weeks'
import { Route as TechnicalReportRouteImport } from './routes/technical-report'
import { Route as OrganizationRouteImport } from './routes/organization'
import { Route as IntroductionRouteImport } from './routes/introduction'
import { Route as ConclusionsRouteImport } from './routes/conclusions'
import { Route as AcknowledgementsRouteImport } from './routes/acknowledgements'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WeeksIndexRouteImport } from './routes/weeks.index'
import { Route as WeeksWeekRouteImport } from './routes/weeks.$week'

const WeeksRoute = WeeksRouteImport.update({
  id: '/weeks',
  path: '/weeks',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicalReportRoute = TechnicalReportRouteImport.update({
  id: '/technical-report',
  path: '/technical-report',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationRoute = OrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const IntroductionRoute = IntroductionRouteImport.update({
  id: '/introduction',
  path: '/introduction',
  getParentRoute: () => rootRouteImport,
} as any)
const ConclusionsRoute = ConclusionsRouteImport.update({
  id: '/conclusions',
  path: '/conclusions',
  getParentRoute: () => rootRouteImport,
} as any)
const AcknowledgementsRoute = AcknowledgementsRouteImport.update({
  id: '/acknowledgements',
  path: '/acknowledgements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WeeksIndexRoute = WeeksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WeeksRoute,
} as any)
const WeeksWeekRoute = WeeksWeekRouteImport.update({
  id: '/$week',
  path: '/$week',
  getParentRoute: () => WeeksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acknowledgements': typeof AcknowledgementsRoute
  '/conclusions': typeof ConclusionsRoute
  '/introduction': typeof IntroductionRoute
  '/organization': typeof OrganizationRoute
  '/technical-report': typeof TechnicalReportRoute
  '/weeks': typeof WeeksRouteWithChildren
  '/weeks/$week': typeof WeeksWeekRoute
  '/weeks/': typeof WeeksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acknowledgements': typeof AcknowledgementsRoute
  '/conclusions': typeof ConclusionsRoute
  '/introduction': typeof IntroductionRoute
  '/organization': typeof OrganizationRoute
  '/technical-report': typeof TechnicalReportRoute
  '/weeks/$week': typeof WeeksWeekRoute
  '/weeks': typeof WeeksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acknowledgements': typeof AcknowledgementsRoute
  '/conclusions': typeof ConclusionsRoute
  '/introduction': typeof IntroductionRoute
  '/organization': typeof OrganizationRoute
  '/technical-report': typeof TechnicalReportRoute
  '/weeks': typeof WeeksRouteWithChildren
  '/weeks/$week': typeof WeeksWeekRoute
  '/weeks/': typeof WeeksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acknowledgements'
    | '/conclusions'
    | '/introduction'
    | '/organization'
    | '/technical-report'
    | '/weeks'
    | '/weeks/$week'
    | '/weeks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acknowledgements'
    | '/conclusions'
    | '/introduction'
    | '/organization'
    | '/technical-report'
    | '/weeks/$week'
    | '/weeks'
  id:
    | '__root__'
    | '/'
    | '/acknowledgements'
    | '/conclusions'
    | '/introduction'
    | '/organization'
    | '/technical-report'
    | '/weeks'
    | '/weeks/$week'
    | '/weeks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcknowledgementsRoute: typeof AcknowledgementsRoute
  ConclusionsRoute: typeof ConclusionsRoute
  IntroductionRoute: typeof IntroductionRoute
  OrganizationRoute: typeof OrganizationRoute
  TechnicalReportRoute: typeof TechnicalReportRoute
  WeeksRoute: typeof WeeksRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weeks': {
      id: '/weeks'
      path: '/weeks'
      fullPath: '/weeks'
      preLoaderRoute: typeof WeeksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technical-report': {
      id: '/technical-report'
      path: '/technical-report'
      fullPath: '/technical-report'
      preLoaderRoute: typeof TechnicalReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization': {
      id: '/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof OrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/introduction': {
      id: '/introduction'
      path: '/introduction'
      fullPath: '/introduction'
      preLoaderRoute: typeof IntroductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conclusions': {
      id: '/conclusions'
      path: '/conclusions'
      fullPath: '/conclusions'
      preLoaderRoute: typeof ConclusionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acknowledgements': {
      id: '/acknowledgements'
      path: '/acknowledgements'
      fullPath: '/acknowledgements'
      preLoaderRoute: typeof AcknowledgementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weeks/': {
      id: '/weeks/'
      path: '/'
      fullPath: '/weeks/'
      preLoaderRoute: typeof WeeksIndexRouteImport
      parentRoute: typeof WeeksRoute
    }
    '/weeks/$week': {
      id: '/weeks/$week'
      path: '/$week'
      fullPath: '/weeks/$week'
      preLoaderRoute: typeof WeeksWeekRouteImport
      parentRoute: typeof WeeksRoute
    }
  }
}

interface WeeksRouteChildren {
  WeeksWeekRoute: typeof WeeksWeekRoute
  WeeksIndexRoute: typeof WeeksIndexRoute
}

const WeeksRouteChildren: WeeksRouteChildren = {
  WeeksWeekRoute: WeeksWeekRoute,
  WeeksIndexRoute: WeeksIndexRoute,
}

const WeeksRouteWithChildren = WeeksRoute._addFileChildren(WeeksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcknowledgementsRoute: AcknowledgementsRoute,
  ConclusionsRoute: ConclusionsRoute,
  IntroductionRoute: IntroductionRoute,
  OrganizationRoute: OrganizationRoute,
  TechnicalReportRoute: TechnicalReportRoute,
  WeeksRoute: WeeksRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
